[package]
name = "myweb"
version = "0.1.0"
authors = ["Francisco Manzano <keoh77@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
serde_derive = "1.0.87"
serde = "1.0.87"
serde_json = "1.0.38"