[package]
name = "myweb"
version = "0.1.0"
authors = ["Francisco Manzano <keoh77@gmail.com>"]
edition = "2018"

[dependencies]
iron = "0.6.0"
router = "0.6.0"
time = "*"

[dependencies.logger]

git = "https://github.com/iron/logger.git"